DLTcollab/sse2neon

sse2neon.h, tests/impl.cpp, tests/impl.h
Rebase of https://github.com/DLTcollab/sse2neon/pull/9
Verified working in a relatively complex code base that uses them. As well as the unit tests that are implemented.
_mm_mul_epu32 currently defaults to c code as the neon version only compiles with -fpermissive (and the performance gain is questionable)
Keeping the neon version in place but not as default makes it easier for others to experiment/improve on it.
=>  Implement _mm_sub_epi64 and _mm_mul_epu32

sse2neon.h, tests/impl.cpp, tests/impl.h
The result of comparing with NaN is called unordered.
It is different from equal, greater than or less than.
The commit returns the correct value of the single-precision
floating-point comparison instructions when the comparison result
is unordered.
Close #12.
=> fix: Fix single-precision floating-point comparison instructions

Makefile, sse2neon.h, tests/impl.cpp, tests/impl.h
Rewritten to a clean branch to make the commit log cleaner.
Doesn't have all the new tests, but I am working on an easier test suite which I will add in a later PR.
Improved:
- Fixed a few typos
- Fixed `_mm_alignr_si128` not working on Clang (fixes #15)
- Change `__m128i` to `int64x2_t` to make GCC vector extension overloads compatible
- Use `__builtin_shufflevector` on Clang when possible
- `_mm_movemask_epi8`
- `_mm_sign_*`
- `_mm_mul_epu32`
- ~~Better handling of out-of-range shifts, checks can be disabled with a macro if shifts are known to be in range~~
- ~~Use variable shifts instead of immediate shifts due to Clang's stricter constant rules for `_mm_slli_epi*`, `_mm_srli_epi*`, and `_mm_srai_epi*`~~
- Vectorised ARMv7 fallback for `_mm_shuffle_epi8`
- Use `vzip1` and `vzip2` on …
=> Finish almost all integer intrinsics

.travis.yml, Makefile, tests/impl.cpp
Make it possible to run the testsuite on both aarch64 and on x86.  When running
the tests on x86, each test executes native sse2 instructions and verifies that
the check part of the tests is correct.
=> run make check on x86

sse2neon.h, tests/impl.cpp, tests/impl.h
_mm_malloc is a wrapper to posix_memalign(), which is specified in
POSIX.1-2001 and POSIX.1-2008.
=> Implement _mm_malloc and _mm_free

sse2neon.h, tests/impl.cpp, tests/impl.h
The patch passes `make check` on both aarch64 and x86_64.
=> implement mm_sll_epi16

tests/impl.cpp, tests/impl.h
passes `make check` on x64 and a64.
=> add test for _mm_maddubs_epi16

sse2neon.h
This fixes two problems when compiling with gcc-9.3 from Ubuntu 20.04.
=> fix compile errors with gcc-9.3

sse2neon.h, tests/impl.cpp, tests/impl.h
Both ARMv8-A and ARMv7-A specific NEON instructions are supported.
Close #26
=> Implement _mm_popcnt_u32/_mm_popcnt_u64

sse2neon.h, tests/impl.cpp, tests/impl.h
The intrinsic conversion is slightly different on ARM 32-bit
architecture since it does not support float64x2_t data type.
The __m128d data type is treated as float32x4_t and the ARM 64-bit
intrinsics are avoided using on ARM 32-bit architecture.
Close #35.
=> feat: Implement _mm_load_sd

sse2neon.h
Both clang and gcc-10 support "__has_builtin", which evaluates the
existence of specified builtin function. __builtin_shufflevector might
be implemented in newer gcc releases, and this patch attempts to take
a flexible approach to detect its presence.
More about "__has_builtin":
https://clang.llvm.org/docs/LanguageExtensions.html
GCC 10 provides "__hash_builtin" preprocessor operator:
https://gcc.gnu.org/gcc-10/changes.html
=> Rewrite __builtin_shufflevector check with __has_builtin macro

.ci/check-format.sh, .travis.yml, Makefile
A new script '.ci/check_format.sh' is added
for coding convention check in Travis CI.
The 'make format' target in Makefile is for
following the coding convention.
=> CI: Add coding convention check

.travis.yml
Developer Ecosystem Engineering from Apple submitted the performance tuning changes for Apple Silicon, and newer toolchains are required to validate.
TODO: add CI matrix to build with the default packages provided by Ubuntu LTS as well.
=> CI: Prefer latest gcc/clang for validating purpose

sse2neon.h
The test suite is modified to fit the requirement
of 4 input __m128 parameters of _MM_TRANSPOSE4_PS.
The test cases of different input data would be slightly fewer than
before.
Close #10.
=> feat: Implement _MM_TRANSPOSE4_PS macro

sse2neon.h
Clang provides overloaded builtins allowing generation of non-temporal
memory accesses.
Reference: https://clang.llvm.org/docs/LanguageExtensions.html
=> Rewrite _mm_stream_si128 with non-temporal load/store builtin

sse2neon.h
This remove unnecessary instruction and let's rely on the compiler. See https://gcc.godbolt.org/z/WWEq9L
__builtin_popcount is presented in all compilers where __GNUC__ is defined, also it is not recommended for all compilers to use __has_builtin for old functions, see note [here](https://clang.llvm.org/docs/LanguageExtensions.html#has-builtin)
=> Improve the performance of popcnt function

sse2neon.h
Clang and gcc-10 supports macro __has_builtin, and GCC <= 9 lacks of the
support. This patch attempts to make a limited list for the builtin
functions that we might make use of.
=> Define macro __has_builtin for GCC prior to 10

tests/impl.cpp
Rename the parameters of the validation functions for better meaning.
Unify the parameter order and function naming.
Close #58.
=> refactor: Unify validation functions in test suite

sse2neon.h
Aarch64 has an accurate instruction vsqrtq_f32, which calculates
the square root for each vector element in the source SIMD and FP
register, places the result in a vector, and writes the vector to
the destination SIMD and FP register. Intrinsic _mm_sqrt_ps can be
implemented with this instruction for better accuracy.
=> Reimplement accurate _mm_sqrt_ps for A64

.travis.yml
The version 10 has a bug with inline assembly.
Please check the following link for more detail:
https://github.com/DLTcollab/sse2neon/pull/71#discussion_r454850578
=> CI: Change clang-format version from 10 to 6

README.md, tests/impl.h
The classification can help the developer find the unimplemented
intrinsic functions quickly.
The classification is referenced from:
https://software.intel.com/sites/landingpage/IntrinsicsGuide/#
=> refactor: Classify intrinsic functions

tests/impl.h
Only mark those intrinsics which have not implemented the test yet.
=> refactor: Remove unnecessary comments of test

sse2neon.h
We shall detect the configurations of clang/gcc in the presence of
NEON-based intrinsics.
=> Check and set build option for Arm/Aarch64 targets

sse2neon.h, tests/impl.cpp, tests/impl.h
Hi,
I have implemented, using the AARCH64 Neon intrinsics, the following functions : 
_mm_cvtpd_ps 
_mm_cvtps_pd
_mm_castpd_si128
_mm_fmadd_ps,
_mm_addsub_ps
_mm_load_pd
_mm_loadu_pd
_mm_store_pd
_mm_storeu_pd
I have got some more new additions which comes from my simd_utils library, but it seemed too much for one pull request.
Please let me know if you need modifications to this pull request.
=> AArch64 implementation of PS FMA and ADDSUB, and some PD load/store/convert

sse2neon.h, tests/impl.cpp, tests/impl.h
Intrinsic "_mm_dp_ps" performs conditional multiplication for
single-precision floating-point elements, sum the four
products and conditionally store the sum. To improve the accuracy
of floating-point summation, Kahan algorithm is used for each
operation. This patch also introduced AArch64-friendly shortcuts for
certain inputs.
=> Implement _mm_dp_ps

README.md, sse2neon.h, tests/impl.cpp
The mapping between SSE2 _mm_min_ps/_mm_max_ps and NEON
vminq_f32/vmaxq_f32 is not accurate, that would give
inconsitent rendering (e.g. holes, NaN pixels). This patch introduces
tunable configuration and precise implementation of _mm_min_ps and
_mm_max_ps. The precise implementation is built by default.
Close #57
=> Implement precise _mm_min_ps/_mm_max_ps

sse2neon.h
There is a powerful NEON instruction `vtrnq_f32` which can transpose elements in place. We can make use of this instruction.
However, we lack of test cases which validate the combination of several intrinsics. Here is the simplified test program for macro `_MM_TRANSPOSE4_PS`:
```c
void simd8x8Transpose32b(__m128i *pBuffer) {
__m128 tmp[16];
for (int n = 0; n < 16; n++)
tmp[n] = _mm_castsi128_ps(pBuffer[n]);
_MM_TRANSPOSE4_PS(tmp[0], tmp[2], tmp[4], tmp[6]);
_MM_TRANSPOSE4_PS(tmp[1], tmp[3], tmp[5], tmp[7]);
_MM_TRANSPOSE4_PS(tmp[8], tmp[10], tmp[12], tmp[14]);
_MM_TRANSPOSE4_PS(tmp[9], tmp[11], tmp[13], tmp[15]);
for (int n = 0; n < 8; n += 2) {
pBuffer[n] = _mm_castps_si128(tmp[n]);
pBuffer[n + 1] = _mm_castps_si128(tmp[n + 8]);
pBuffer[n + 8] = _mm_castps_si128(tmp[n + 1]);
pBuffer[n + …
```
=> Rewrite _MM_TRANSPOSE4_PS with NEON instruction

sse2neon.h, tests/impl.cpp, tests/impl.h
Intrinsic _mm_srai_epi16 should consider the case when imm8[7:0] > 15.
=> Handle the constant range for _mm_srai_epi16 properly

sse2neon.h
=> Improve _mm_movemask_ps for A64

sse2neon.h
There were two _mm_srai_epi32 implementations: one was the inline function; another was the macro. According to Intel manual, the operation of intrinsic _mm_srai_epi32 is illustrated as following:
__m128i _mm_srai_epi32 (__m128i a, int imm8)
FOR j := 0 to 3
i := j*32
IF imm8[7:0] > 31
dst[i+31:i] := (a[i+31] ? 0xFFFFFFFF : 0x0)
ELSE
dst[i+31:i] := SignExtend32(a[i+31:i] >> imm8[7:0])
FI
ENDFOR
The original inlined function would produce different behavior, and this patch drops it for the sake of correctness.
=> Drop incorrect _mm_srai_epi32 implementation

sse2neon.h
Remove the useless data type __m64i and make data type __m64 consist of
integer elements.
=> fix: Replace data type __m64i with __m64

sse2neon.h, tests/impl.cpp, tests/impl.h
These intrinsic functions are the same as the _mm_avg_pu8 and
_mm_avg_pu16.
=> feat: Implement _m_pavgb and _m_pavgw

.gitignore
Bash script '.ci/cross-tool.sh' would download cross-compiling tools
for testing. However, these tools are not included in gitignore.
=> chore: Add cross-compiling tools into gitignore

sse2neon.h, tests/impl.cpp
The implementation just calls the __mm_store_pd since the only
difference is the memory alignment restriction.
Related #81.
=> feat: Implement A32 counter part of _mm_storeu_pd

sse2neon.h
_mm_slli_epi16 would set all the destination bits to zeros when imm8
is greater than 15.
see https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm_slli_epi16
=> fix: Fix condition for setting zeros _mm_slli_epi16

sse2neon.h, tests/impl.cpp
Fix wrong A64 implementation of _mm_cvtpd_ps and _mm_cvtps_pd.
Add A32 implementation of _mm_cvtpd_ps, _mm_cvtps_pd and
_mm_castpd_si128.
Add the corresponding tests.
Close #81.
=> feat: Implement __m128d conversion and casting

sse2neon.h, tests/impl.cpp
In A64, `_mm_hadds_epi16` applies `vuzp1q_s16` and `vuzp2q_s16`.
=> refactor: Use UZP for A64 in _mm_hadds_epi16

sse2neon.h, tests/impl.cpp
The original conversion of _mm_sign_epi8 was opposite to what document
mentioned. Here, the bug of the conversion has been fixed, and we add
A64 operation and corresponding test case.
Close #149
=> refactor: Tweak and add test case for _mm_sign_epi8

sse2neon.h, tests/impl.cpp
In A64, `_mm_hsubs_epi16` applies `vuzp1q_s16` and `vuzp2q_s16`.
=> refactor: Use UZP for A64 in _mm_hsubs_epi16

sse2neon.h
The precise `_mm_min_ps` can be implemented as
```c
FORCE_INLINE __m128 _mm_min_ps(__m128 a, __m128 b)
{
return vbslq_f32(vcltq_f32(a, b), a, b);
}
```
Derived from https://github.com/lighttransport/embree-aarch64/pull/33
=> Improve _mm_{max,min}_ps

sse2neon.h, tests/impl.cpp
The behavior of _mm_sign_epi16 is opposite. The wrong behavior has been
fixed in this PR. A64 operation and test case have been appended in
this PR, too.
=> fix: Fix wrong behavior of _mm_sign_epi16

sse2neon.h, tests/impl.cpp
The behavior of _mm_sign_epi16 is opposite. The wrong behavior has been
fixed in this PR. A64 operation and test case have been appended in
this PR, too.
=> fix: Fix wrong behavior of _mm_sign_epi32

sse2neon.h, tests/impl.cpp
_mm_slli_epi32 was not able to take non-constant value for imm.
Test case has been added in this PR, too.
=> refactor: Allow non-constant input _mm_slli_epi32

sse2neon.h, tests/impl.cpp
_mm_slli_epi64 was not able to take non-constant value for imm.
Test case has been added in this PR, too.
=> refactor: Allow non-constant input _mm_slli_epi64

tests/impl.h
test `test_mm_setzero_pd` was not declared in `impl.h`
=> test: Add declaration of test_mm_setzero_pd

.github/CODEOWNERS
Codeowners on github would be automatically requested when a new PR is
opened.
=> chore: Apply codeowner rules

.ci/check-format.sh, .github/workflows/github_actions.yml, Makefile
check-format.sh:
The clang-format should use version 6 instead of 10.
Discussion: #71 (comment)
Makefile:
The returned processor type of Github Actions arm 32-bit platform is armv7l,
hence it should be included in Makefile detection.
github_actions.yml:
The non-x86 CPU architecture is offered by https://github.com/uraimo/run-on-arch-action.
The related YAML should be written by following the document rule.
Close #253.
=> CI: Add the yaml file for Github Actions

tests/impl.cpp, tests/impl.h
Declare all the intrinsics in impl.h and add the corresponding tests
in impl.cpp with returning `TEST_UNIMPL`. The order of declarations in
impl.h is based on the order on official guide.
=> feat: Declare unimplemented intrinsics

sse2neon.h, tests/impl.cpp
Mapping `_mm_blendv_ps` intrinsics directly with `vbslq_f32` is not an
accurate implementaion. We should take signed shift right then call
`vbslq_f32`.
=> fix: Complete mm_blendv_ps with signed shift right 

.github/workflows/github_actions.yml, tests/impl.cpp
The .ci/check-format script does not return error when
the clang-format-6.0 is not installed.
Currently, the commit makes sure the required software is installed.
The fixing of the script will be done in the future.
=> CI: Make sure the coding convention is checked

sse2neon.h
The reversion is for performance improvement.
The AArch64 implementation execution time is around 100ns,
while the ARM 32-bit version is around 90ns.
Close #219.
=> perf: Revert AArch64 implementation of __mm_movemask_epi8

sse2neon.h, tests/impl.cpp
The original version does not accept the third argument of
_mm_alignr_epi8 larger than 15 with GCC.
However, the fixed version still has the problem on ARM platform with
Clang-10.
Clang-10 would check the third argument of vextq_u8 in different if-else
condition and generate error message "argument value is outside the
valid range [0, 15]".
=> fix: Fix _mm_alignr_epi8 implementation and add test

tests/impl.cpp
`_mm_store1_pd` and `_mm_store_pd1` share the same implementation, so
we can simply call the test of `_mm_store_pd1` for `_mm_store1_pd`
=> test: Add test for _mm_store1_pd

tests/impl.cpp
`_m_pavgb` and `_m_pavgw` share the same implementation of
`_mm_avg_pu8` and `_mm_avg_pu16`, respectively, so we can simply call
the tests of `_mm_avg_pu8` and `_mm_avg_pu16`.
=> test: Add tests for _m_pavgb and _m_pavgw

sse2neon.h, tests/impl.cpp
https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm_blend_ps
tested on NVIDIA XAVIAR
test for x86 disable due immediate 4 bit restriction
=> feat: Implement _mm_blend_ps with test

sse2neon.h, tests/impl.cpp, tests/impl.h
Dear All, 
I have implemented _MM_SET_ROUNDING_MODE using the information found on the [Arm Armv8-A Architecture Registers](https://developer.arm.com/docs/ddi0595/e/aarch32-system-registers/fpscr).
At the moment the test only fails for _MM_ROUND_TOWARD_ZERO on aarch32, the other ones seem to behave correctly.
=> implemented _MM_SET_ROUNDING_MODE

sse2neon.h, tests/impl.cpp
Clang-10 would check the third argument of vext_u8 in different
condition and generate error message "argument value is outside
valid range [0, 7]".
Therefore, the coressponding test is ignored.
=> feat: Implement _mm_alignr_pi8

sse2neon.h, tests/impl.cpp
The intrinsics which are implemented in this PR, actually share the
same implementation listed as following, so we use the implemtation
directly.
"_m_pinsrw": "_mm_insert_pi16"
"_m_pmaxsw": "_mm_max_pi16"
"_m_pmaxub": "_mm_max_pu8"
"_m_pminsw": "_mm_min_pi16"
"_m_pminub": "_mm_min_pu8"
=> feat: Implement intrinsics with the corresponding intrinsics

sse2neon.h, tests/impl.cpp
_mm_ucomieq_ss, _mm_ucomige_ss, _mm_ucomigt_ss,_mm_ucomile_ss
,_mm_ucomilt_ss, _mm_ucomineq_ss share the same implementation of
_mm_comieq_ss, _mm_comige_ss, _mm_comigt_ss,_mm_comile_ss, _mm_comilt_ss
, _mm_comineq_ss.
Therefore, we can call the tests of _mm_comieq_ss, _mm_comige_ss,
_mm_comigt_ss,_mm_comile_ss, _mm_comilt_ss, _mm_comineq_ss directly.
=> test: Call tests with the same implementation

sse2neon.h
To match SSE more closely, at the cost of performance. Similar to the existing option for more precise min/max.
For embree/embree#316.
=> Options for more precise versions of div, rcp, sqrt, rsqrt

tests/impl.cpp
`d0` and `d1` are not initialized before validation, so it would cause warnings
=> fix: Initialize variable before validation

sse2neon.h, tests/impl.cpp
GCC version before 11 does not implement intrinsic functions
_mm_storeu_si16 and _mm_storeu_si32.
The testing should be modified after the GCC 11 releases.
Check https://gcc.gnu.org/bugzilla/show_bug.cgi?id=95483 for the
bug information.
=> feat: Implement _mm_storeu_si<16-64>

sse2neon.h, tests/impl.cpp
All f's heximal number is hard to distinguish how many "f" it has, and
may cause barrier during debugging. Therefore, they are replaced with
macro in corresponding bit size, or type casting -1.
=> refactor: Replace f's with UINT[64|16|8]_C macro

sse2neon.h
The resultant sign bit from a signed-saturated subtraction is a `greater than` comparison predicate.
=> Optimize _mm_cmpgt_epi64 for ARMv7

sse2neon.h
The comment of GCC bug in 2021-01-12 said that the intrinsic
vld1q_u8_x4 is not implemented in GCC.
Ref:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=71233#c73
However, the GCC 10.3 released in 2021-04-08 has fixed the problem for
AArch64 CPU architecture, not for ARM CPU architecture.
Ref:
https://github.com/gcc-mirror/gcc/commit/391625888d4d97f9016ab9ac04acc55d81f0c26f
The Github Actions CI has change the GCC compiler from 10.1 to 10.3,
hence we should take care of the version well.
=> fix: Add correct GCC version checking of vld1q_u8_x4

.ci/check-format.sh
The commit is for the developers who can not install the
clang-format-6.0.
They can view the correct coding style from the Github Actions CI.
=> CI: Show the difference before and after clang-format

sse2neon.h
On M1-based machines, some intrinsics would fall into the second
if-statement, which causes setting the result twice.
=> fix: Avoid set result twice in __extension__

sse2neon.h, tests/impl.cpp
test: Fix testing of _mm_round_ps
The test covers more scenario of different rounding mode.
The validation does not have to consider inaccuracy.
fix: Fix the implementation of _mm_round_ps
Simplify the implmentation of rounding mode _MM_FROUND_TO_ZERO.
Fix the implementation of rounding mode _MM_FROUND_CUR_DIRECTION.
=> Fix _mm_round_ps

sse2neon.h
`_mm_aesenclast_si128` emits a warning with clang++.
```
sse2neon.h:6053:9: error: array designators are a C99 extension [-Werror,-Wc99-designator]
[0] = {SSE2NEON_sbox[vreinterpretq_nth_u8_m128i(a, 0)],
^~~
1 error generated.
```
The array designators are not necessary at all, so this simply removes them.
=> fix: Avoid -Wc99-designator warning

sse2neon.h, tests/impl.cpp
Avoid data lost caused by conversion from floating point to integer.
Use the correct way to detect whether the floating point which has the
exact integer value is odd or even.
=> fix: Fix Bankers rounding algorithm

sse2neon.h
The implementation should not convert the 32-bit floating point to
32-bit integer.
It would cause the data truncation if the 32-bit floating point contains the
value which is out of the range of 32-bit integer.
=> fix: Avoid data truncation of _mm_cvttss_si64

README.md, sse2neon.h
Reorder the intrinsics with the SSE, SSE2, SSE3, SSSE3, SSE4.1 and
SSE4.2 classes.
=> refactor: Reorder intrinsics in sse2neon.h

sse2neon.h
Some conditional operations can be replaced with binary operations
which should be able to accelerate the functions by removing branch
prediction.
=> refactor: Replace conditional op with binary operation

sse2neon.h
See https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm_cvtepu8_epi16 that precises that it operates on 8 uint8 values
=> _mm_cvtepu8_epi16(): fix comment

sse2neon.h
Replace the implementation in C to NEON implementation in which way
all the operation can be handled in register, and it should accelerate
the function.
=> refactor: Replace C operations with SIMD

tests/impl.cpp
The iterating number which is given to the all tests as function
argument is too common, so I may conflict with the iterator
variable "i" in each tests. We can simply rename to other name.
=> refactor: Rename test iteration count

sse2neon.h, tests/impl.cpp, tests/impl.h
Danila Kutenin pointed out:
> Technically speaking, _mm_fmadd_ps is not an SSE extension, this was
> introduced with fma extension which took place even after AVX.
To clarify the purpose of SSE2NEON, this pach would drop the existing
FMA implementation.
Related: #82
=> Drop FMA intrinsic

tests/impl.cpp
The intrinsic _mm_loadu_si[16|32] have been supported since GCC 11.
=> test: Check GCC version for _mm_loadu_si[16|32]

sse2neon.h
Using just "uint", sse2neon does not compile on macOS using Apple's
clang variant. Changing "uint" to "uint32_t" solves the problem.
=> _mm_cvtps_pi8: Change uint to uint32_t

sse2neon.h, tests/impl.cpp
Fix the following warning which is shown on Apple M1
```
warning: implicit conversion from 'int' to 'int8_t' (aka 'signed char')
changes value from 135 to -121 [-Wconstant-conversion]
vand_s8(vreinterpret_s8_m64(b), vdup_n_s8((0x1 << 7 | 0x07)));
~~~~~~~~~  ~~~~~~~~~^~~~~~
```
=> fix: Fix implicit conversion warning

sse2neon.h, tests/impl.cpp, tests/impl.h
The behavior of denormal number and flush zero mode has not been
fully investigated yet.
The validation of __MM_SET_FLUSH_ZERO_MODE should be added in the
future.
Related to #465.
=> feat: Implement _MM_[GET|SET]_FLUSH_ZERO_MODE

tests/impl.cpp
The templates can avoid extra casting.
The validations are removed since the corresponding intrinsic testings
have been implemented.
=> test: Rewrite load rountine functions to templates

sse2neon.h, tests/impl.cpp
The test has been rewritten for testing more immediate values.
The selected values are able to represent different scenarios.
The implementation replaces vextq_u8() with vld1q_u8() since the latter
does not require constant immediate value.
As the immediate value is not required, the implementation can be
changed from macro to function.
The commit fixes the issue #482 as well.
Close #482.
=> refactor: Rewrite _mm_alignr_epi8() to function

sse2neon.h, tests/impl.cpp
Implementation:
Rewrite conditional statement with bitwise AND operation.
Fix _mm_slli_si128() and _mm_srli_si128() intrinsics
and rewrite as functions.
Remove extra conditional statements for simplicity.
Testing:
Rewrite conditional statement with bitwise AND operation.
Test shift value in a reasonable range.
Test shift intrinsics required immediate shift value with different
input data.
Make the testing code follow the sequence order as variables declaration,
C implementation, SIMD implmentation and validation.
Close #393.
=> fix: Rewrite implementation and testing of shift intrinsics

sse2neon.h
The NaN handling is included in the NEON comparison intrinsics.
The commit removes the extra NaN checking and rewrites some code
for simplicity.
=> refactor: Remove extra NaN checking in comparison intrinsics

tests/common.h, tests/impl.cpp
Use the macro provided by C header file math.h instead of implementing
one.
=> refactor: Replace functions for checking NaN

README.md, sse2neon.h
The commit adds the new macro SSE2NEON_PRECISE_DP for precise
implementation of _mm_dp_pd().
The precise implementation removes the possible extra multiplications.
Enable the macro might decrease the performance but the behaviour
would be matched with the intrinsic description of Intel Intrinsics Guide.
Close #480.
=> fix: Add precise implementation of _mm_dp_pd()

tests/impl.cpp
According to https://gcc.gnu.org/bugzilla/show_bug.cgi?id=98612,
the intrinsics _mm_comi[eq|le|lt|neq]_[sd|ss] do not return the
correct value when comparing with NaN values.
The testing would be unimplemented when using GCC.
=> test: Add compiler detection for NaN comparison testing

tests/impl.cpp
One of the comparison result should be the value with all bits set to 1.
Use getNAN() would be confusing for the programmer, although it does
meet the requirement since the NaN it returned has all bits set to 1.
=> refactor: Replace confusing code for comparison result

sse2neon.h, tests/impl.cpp
Take not greater than (ngt) as an example:
When comparing with NaN values, not greater than (ngt) is not equal
to less equal (le).
The implementation and testing of not greater than (ngt) should be the reverse
of greater than (gt).
Hence, the testing should add the input data of NaN values and the
implementation and testing should be rewritten.
=> fix: Fix the intrinsics of comparing floating points

sse2neon.h
There are places where `asm volatile` is used and others which use `__asm__ __volatile__`.
This PR makes consistent use of the latter since it's more widely supported.
=> asm volatile -> __asm__ __volatile__

tests/common.cpp
The error would happen under the following situation:
For the parameter `t[_i]` and `f_i` are both zero, `TEST_SUCCESS` should be returned, but `df_i` is gotten by dividing `f_i`. Therefore, `df_i` would be `NaN` instead of zero.
close #514
=> fix: Fix dividing zero error in validateFloatError

sse2neon.h
The C language does not allow initializing a variable with a function
call, but C++ accepts. This patch makes it work with both C and C++,
and (contrary to just removing "static") keeps the optimization at least
in C++ code.
Close #505
=> Fix compilation with standardized C compilers

README.md, sse2neon.h
This adds support for using sse2neon when building 32-bit executables to run on ARMv8 architectures.  Prior to this change, you could not use sse2neon when building a 32-bit executable while targeting ARMv8.  So you couldn't do this:
$ clang++ -O2 -mcpu=cortex-a73 -mfpu=neon-fp-armv8 myprogram.cpp
when the target was armv7l-unknown-linux-gnueabihf, as sse2neon looks for __ARM_ARCH == 7, or __aarch64__ defined, and neither is true for a 32-bit executable targeting ARMv8.
=> Add support for 32-bit targets on ARMv8 architectures

sse2neon.h
Enable the use of CRC and directed rounding intrinsics when
targeting ARMv8 32-bit.  These are intrinsics that were added
in ARMv8 for both the 32-bit execution mode and AArch64.
=> Use CRC and directed rounding intrinsics on A32

tests/impl.cpp
_mm_store_si128 and _mm_stream_si128 are aligned in 16 bytes
close #521
=> fix: Fix alignment in tests

sse2neon.h
Complex arguments are not always handled properly by _mm_srai_epi32.
Arguments like below will properly evaluate
`input[i] = _mm_srai_epi32(input[i], new_sqrt2_bits - 1 + shift);`
This also resolves 5 failing tests
```
[  FAILED  ] 5 tests, listed below:
[  FAILED  ] TX_ASM/InvTxfm2dAsmTest.sqr_txfm_match_test/0, where GetParam() = (0x102c7b198, 8)
[  FAILED  ] TX_ASM/InvTxfm2dAsmTest.sqr_txfm_match_test/1, where GetParam() = (0x102c7b198, 10)
[  FAILED  ] TX_ASM/InvTxfm2dAsmTest.lowbd_txfm_match_test/0, where GetParam() = (0x102c7b198, 8)
[  FAILED  ] TX_ASM/InvTxfm2dAddTest.svt_av1_inv_txfm_add/0, where GetParam() = (0x102c7d800, 8)
[  FAILED  ] SSE4_1/AV1SelfguidedFilterTest.CorrectnessTest/0, where GetParam() = (0x102cd4f20)
```
=> Improve _mm_srai_epi32 to handle complex arguments

sse2neon.h
Signed-off-by: Philip Balister <philip@balister.org>
=> gcc-12 still does not support vld1q_u8_x4 for 32 arm builds.

sse2neon.h, tests/impl.cpp
The `asm volatile` keywords in `_rdtsc` and its relevant test case do not have the same style of others (i.e., `__asm__ __volatile__`). Therefore, I alter these keywords into the same style.
=> Alter "asm volatile" keywords into same style in _rdtsc

sse2neon.h
C supports designated initialization of arrays, but C++ does not. The one usage of it does not serve a functional purpose and so can be removed. This code was triggering warnings under clang and errors under MSVC.
=> Remove designated initialization of an array

sse2neon.h
Use the vector extract instruction (ext) to implement `_mm_srli_si128`,
`_mm_slli_si128` and `_mm_alignr_epi8`, significantly improving performance
by avoiding memory.
These were originally changed in #483 and #484 to instead use a store
followed by a shifted load. This was done in order to resolve issue
#482, where the compiler would throw an error if there were an invalid
immediate in the intrinsic arguments after the macros are expanded.
These commits avoid the recurrence of this issue by guarding the
immediate arguments with additional (redundant) ternary expressions.
These are evaluated at compile time and should cause no performance
loss; they only prevent the compilers from attempting to propagate
invalid immediates. This does now require that the immediate argument
to these …
=> Reintroduce `ext`-based implementations for shift intrinsics

sse2neon.h, tests/impl.cpp
Improve performance of several of the float-to-integer intrinsics.
The first commit re-writes `_mm_cvtps_pi8` and `_mm_cvtps_pi16` to use
the signed saturating extract-narrow (`sqxtn`) intrinsic instead of
emulating the saturating-narrow behaviour with several masks.
The second commit adds support for using the round-to-integral
intrinsics introduced by `FEAT_FRINTTS` in Armv8.5-A. These match the
out-of-bounds behaviour specified by the SSE float-to-integer
conversions instead of saturating, so this required a test modification.
Sample codegen diffs are provided in the individual commit messages.
=> Improve performance of float-to-integer intrinsics

sse2neon.h
GCC versions < 12 do not support `__builtin_shufflevector`, though they do
support an alternative builtin named `__builtin_shuffle`. It requires that
the indices are passed as an integer vector as opposed to variadic
arguments.
This enables us to benefit from potentially improved and better
performing code generation for intrinsics that are implemented with this
builtin.
=> Support `__builtin_shuffle` as an alternative to `__builtin_shufflevector`

tests/impl.cpp
Simplify the macro names in `_mm_cmpestr` test cases.
Close #544.
=> Simplify `_mm_cmpestr` test cases

sse2neon.h
This PR contains a set of minor commits that improve the performance of various intrinsics.
Performanced improved for the following intrinsics:
- `_mm_set_ss`
- `_mm_madd_epi16`
- `_mm_testc_si128`
- `_mm_move[l,h]dup_ps`
- `_mm_hadd_epi32`
- `_mm_set_sd`
- `_mm_mpsadbw_epu8`
Please see each individual commit message for a brief summary and change in code generation.
=> Improve performance of various intrinsics

sse2neon.h
Use vector instructions to find the index of the minimum element for _mm_minpos_epu16. This avoids going through several comparisons and is generally much faster when the minimum value is not just the first element.
Codegen difference w/ GCC is included in the commit message.
=> Vectorise _mm_minpos_epu16

.github/workflows/github_actions.yml, .gitignore, Makefile, tests/binding.cpp, tests/impl.cpp
Add Windows CI build using [llvm-mingw](https://github.com/mstorsjo/llvm-mingw), a standalone clang/mingw-w64 toolchain that supports cross compiling.
- Windows builds are produced for x86_64, armv7, and aarch64.
- Tests are only run on x86_64. GitHub does not provide public Windows on ARM64 runners, and there is no qemu-user equivalent on Windows.
- The test framework is updated to support Windows aligned malloc/free APIs.
- The sqrt_sd/pd tests now use an epsilon for comparing results just like the sqrt_ss/ps tests. This is necessary because mingw-w64 implements C sqrt() using x87 rather than SSE.
- In case you are wondering why clang but not GCC: there are currently no builds of GCC that target Windows on ARM64.
=> Add clang/Windows build

.github/workflows/github_actions.yml
This PR assigns the architecture, x86_64 in GitHub Actions job
'host_x86'.
=> fix: Assign architecture in CI job host_x86 

sse2neon.h, tests/impl.cpp
=> feat: Implement _mm_aesdeclast_si128

sse2neon.h
Conduct VTRN to remove bit selection operations.
=> refactor: Optimize aeskeygenassist_si128 in ARM64

sse2neon.h
_mm_unpackhi_epi64 and _mm_unpacklo_epi64 have a lack of ARM64 implementation. This PR adds them.
=> refactor: Add missing ARM64 implementation

.github/workflows/github_actions.yml, Makefile, README.md
The current test has a lack of tests with crypto flag enabled which cause the tests not cover the total implementation.
=> test: Build/run with crypto and/or crc

sse2neon.h
Accelerate _mm_movelh_ps for about 6.71%.
Test benchmark is listed below.
```
old average time: 4.062780e-05
new average time: 3.790102e-05
old time std: 1.375459e-06
new time std: 1.348056e-06
```
The benchmark was generated by following test
```c
const float *_a = impl.mTestFloatPointer1;
const float *_b = impl.mTestFloatPointer2;
__m128 a = load_m128(_a);
__m128 b = load_m128(_b);
clock_t t;
double time_taken;
t = clock();
for (int i = 0; i < 10000; i++) {
old_mm_movehl_ps(a, b);
}
t = clock() - t;
time_taken = ((double) t) / CLOCKS_PER_SEC;
printf("old: %f\n", time_taken);
t = clock();
for (int i = 0; i < 10000; i++) {
new_mm_movehl_ps(a, b);
}
t = clock() - t;
time_taken = ((double) t) / CLOCKS_PER_SEC;
printf("new: %f\n", time_taken);
```
=> refactor: Reimplement _mm_movelh_ps for Arm64

tests/impl.cpp
This PR use X-Macro skill to iterate all the possible immediate numbers for the intrinsics that allow immediate numbers only.
closes #582
=> tests: Cover all immediate numbers

tests/common.h, tests/impl.cpp
This is the first step for conducting the future change of using x-macro in the tests of instrinsics with immediate argument
=> test: Use macro for validate results

README.md, sse2neon.h, tests/common.cpp, tests/impl.cpp
1. Improve precision of `_mm_{rsqrt,rcp}_{ps,ss}`. The precision of this part is guaranteed below 0.1% relative error.
2. Improve precision of `_mm_sqrt_{ps,ss}`. The precision of `_mm_sqrt_{ps,ss}` is guaranteed below $10^{-6}$% relative error on ARMv8-A and $10^{-4}$% relative error on ARMv7-A.
3. Add warnings of `_mm_sqrt_ps` and `_mm_div_ps` for ARMv7-A NEON implementation
as the results are not IEEE754-compliant due to lack of precise square
root and division intrinsic.
4. Add deprecation notice of `SSE2NEON_PRECISE_DIV` and `SSE2NEON_PRECISE_SQRT`
as accuracy has precedence of performance in `_mm_{rsqrt,sqrt,rcp,div}_{ps,ss}`.
Close #526.
=> Improve precision of _mm_{rsqrt,sqrt,rcp,div}_{ps,ss} conversions

sse2neon.h
ARM64 or AMD64 required for the 64-bit version of the _BitScanForward64 intrinsic.
=> Tweak MSVC ifdef guard for _BitScanForward64

tests/impl.cpp
There are no any test cases for testing infinity in `test_mm_{max,min}_{pd,sd}`, which will let user feel confused whether using infinity will work on these conversions or not.
As a result, this PR adds positive/negative infinity test cases for these four intrinsic conversions.
=> Add infinity test in `test_mm_{max,min}_{pd,sd}`

sse2neon.h, tests/impl.cpp
Remove Kahan algorithm in `_mm_dp_ps` to align conversion result with SSE.
Also, apply shortcut when immediate is `0xXF` and target is ARMv8-A.
Last, add more tests for testing possible combinations of immediate
including `0xXF`.
Close #595.
=> Remove Kahan algorithm in `_mm_dp_ps`

.github/workflows/github_actions.yml
This allows tests to run for Windows MSVC ARM64 platforms
=> Add test running for MSVC to CI

README.md, sse2neon.h, tests/common.cpp, tests/impl.cpp
Align result to SSE when input is 0.0f/-0.0f in `_mm_rsqrt_{ps, ss}`.
=> Align result to SSE when input is 0.0f/-0.0f in _mm_rsqrt_{ps, ss}

sse2neon.h
* gcc-13 still does not support vld1q_u8_x4 for 32 bit arm builds.
=> Fix build for gcc-13 and 32 bit arm systems.

sse2neon.h
While building CNDP project (https://github.com/CloudNativeDataPlane/cndp) along with sse2neon.h on aarch64 architecture on Ubuntu 18.04.6 LTS the following build errors were encountered:
../lib/core/arm/sse2neon.h:547:1: error: function declaration isn't a prototype [-Werror=strict-prototypes]
FORCE_INLINE unsigned int _MM_GET_ROUNDING_MODE();
^~~~~~~~~~~~
../lib/core/arm/sse2neon.h:563:1: error: function declaration isn't a prototype [-Werror=strict-prototypes]
FORCE_INLINE __m128i _mm_setzero_si128();
^~~~~~~~~~~~
../lib/core/arm/sse2neon.h:1761:23: error: function declaration isn't a prototype [-Werror=strict-prototypes]
FORCE_INLINE uint64_t _sse2neon_get_fpcr()
^~~~~~~~~~~~~~~~~~
../lib/core/arm/sse2neon.h: In function '_sse2neon_get_fpcr':
../lib/core/arm/sse2neon.h:1761:23: error: …
=> Fixed gcc strict prototype and other build errors

tests/impl.cpp
Use SplitMix64 for fast and deterministic RNG for cross compiler/platform support.
=> Introduce fast and deterministic RNG

.github/workflows/github_actions.yml, Makefile, README.md
Add A32 support in CI.
For @jonathanhue, if possible, kindly leave some suggestions as I have little experience on A32 binary running on Armv8-A.
=> Add A32 support in CI

sse2neon.h, tests/impl.cpp
Bug: `_mm_test_mix_ones_zeros` always returned true.
The function wasn't reducing `zf` and `cf` to a bool before combining them.
The fix proposed here isn't the most efficient, but at least it is correct. 
` _mm_testnzc_si128` is an alias for `_mm_test_mix_ones_zeros`.
Note(s):
The arguments are named incorrectly in the `_mm_test_mix_ones_zeros` documentation[0].
The second argument is the mask, as per the behavior of `_mm_test_mix_ones_zeros` with gcc and clang.
This naming error seems to have propagated through both gcc[1] and llvm[2] headers but not to rust[3] headers or sse2neon[4].
[0] https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=ptest&techs=SSE_ALL&ig_expand=6902
[1] https://github.com/gcc-mirror/gcc/blob/27ce74fa23c93c1189c301993cd19ea766e6bdb5/gcc/c …
=> Fix _mm_test_mix_ones_zeros and _mm_testnzc_si128

sse2neon.h
Clang also defines `__GNUC__` and even in recent Clang versions like 15 this value is 4.
=> Fix Clang showing incorrect GCC version warning

README.md, sse2neon.h
This restores support for SSE2NEON_PRECISE_DIV and SSE2NEON_PRECISE_SQRT with the same level of precision that they had before deprecation in #580.
That changed enabled higher precision by default, but not as high as was possible with the options before. The options were originally added to make Embree and Blender work correctly on Apple Silicion, and tested to need exactly this level of precision.
---
It would be helpful for Blender not to have to maintain either a patched sse2neon or work with different tolerances on x86 and ARM.
=> Restore options for precision of div/rcp/sqrt/rsqrt

sse2neon.h, tests/impl.cpp
Close https://github.com/DLTcollab/sse2neon/issues/624.
=> Optimize CRC intrinisics for targets lacking of CRC extension

README.md, tests/impl.cpp
Cross compiling with gcc-8.3 and gcc-9.2 would cause operand mismatch
error in some tests. The C code of some tests were compiled into
stange instructions. Fixing the error by not running the tests
when using gcc-8.3 and gcc-9.2
fixes https://github.com/DLTcollab/sse2neon/issues/622
=> test: Avoid errors when cross compile by gcc-8.3/9.2

sse2neon.h
On 64bit ARM platforms there is no need to use rcp with NR steps to implement _mm_div_ps as there is an exact instruction for the division. In fact, using an rcp and RN step makes _mm_div_ps have different precision from native SSE, and also makes sse2neon tests to fail.
This change makes it so the SSE2NEON_PRECISE_DIV only adds an extra RN step when building for 32bit ARM platforms. On 64bit platforms it makes _mm_div_ps to have exact result to what this intrinsic provides on X64 platforms. It also fixes regression tests when compiled SSE2NEON_PRECISE_DIV=1.
There is no change in behavior or precision of _mm_div_ps on 32bit ARM platforms.
In order to reproduce the issue this change aims to address, sse2neon tests could be used:
make clean && CXXFLAGS='-DSSE2NEON_PRECISE_DIV=1' make && …
=> Fix with _mm_div_ps when SSE2NEON_PRECISE_DIV=1

sse2neon.h
Some function may be ignored or not well executed if optimization is applied. A classic example is `test test_mm_set_rounding_mode`.
_mm_round_ps is computed in compiling time, in which case, rounding mode changing is ignored.
=> fix: Disable optimization to avoid pontential errors

sse2neon.h, tests/common.h, tests/impl.cpp
Casting vector registers to a pointer or accessing the address of a
variable and then casting it to a different pointer type would
violate strict aliasing rules, potentially causing strict aliasing
errors.
`sse2neon_recast_u64_f64` and `sse2neon_recast_f64_s64` are introduced
to solve this error.
closes #635 #639
=> fix: Fix strict-aliasing errors

tests/impl.cpp
When I ran make check with -O2 passed to ARCH_CFLAGS, the test_mm_dp_pd failed. After debugging, I discovered that a buffer initialized with floats was being cast to a buffer of doubles. The root cause of the test failure was that the exact match of the dot product obtained with intrinsics and calculated with C++ doubles showed differences. This occurred because the numbers were too large, and the dot product had rounding errors.
=> fix test_mm_dp_pd test

sse2neon.h
Thir PR adds support for `clang-cl` (clang, but pretending to be MSVC) to sse2neon on Windows ARM64 platforms. Done as part of some blender work, as using `clang-cl` gives a ~20-40% speedup compared to MSVC.
This is a WIP, as several tests are still failing in `Release` - `Debug` seems to be fine - if anyone has any ideas, please let me know, otherwise I'll keep looking at them through a debugger.
Compiled with the command line (via a VS2022 Native ARM64 Tools CMD window):
```
msbuild sse2neon.vcxproj /p:Configuration=Release /p:CLToolExe=clang-cl.exe /p:CLToolPath=C:\Program Files\LLVM\bin\
```
Failing+skipped tests:
```
Test mm_set_flush_zero_mode         skipped
Test mm_set_rounding_mode           failed
Test mm_setcsr                      failed
Test mm_storeu_si16 …
```
=> Add support for clang-cl on Windows

sse2neon.h
The OPTNONE changes in #638 introduced 25% performance regression in Cycles render engine running on Apple Silicon:
https://projects.blender.org/blender/blender/issues/126408
The reason for this is because as per Clang documentation optnone is incompatible with inline, so none of the functions that is marked as optnone is inlined. The biggest bottleneck for Cycles after that change is _mm_mul_ps.
This change makes it so _mm_mul_ps is inlined and is no longer marked as optnone. This solves the immediate performance regression, and the correctness is verified using the sse2neon's test suit on M2 Ultra and M3 Max, with various optimization levels (default, -O2, -O3).
Additionally, adding -Wstrict-aliasing flag does not introduce new warnings.
=> Fix performance regression after OPTNONE changes

README.md, sse2neon.h, tests/impl.cpp
Revert the previous restriction that some of the functions are forced
to not be optimized when compiling-time optimization options were
given.    
Now it is users' responsibility to ensure the behavior after
optimization.
Shifting the responsibility to the users enables sse2neon the run in
the optimized state in general, but not restricted by some specific
scenarios.
Setting/getting rounding mode directly through fpcr with volatile
keyword could be unstable.
Therefore we use the C99 fesetround()/fegetround() here to ensure
the behavior.
closes #648
=> Allow optimization and use fesetround(), fegetround()

README.md, sse2neon.h
This warning breaks builds of applications using -Werror.
=> Allow to specify -DSSE2NEON_SUPPRESS_WARNINGS to avoid the #warning about optimization issues

sse2neon.h
This macro is defined in emmintrin.h and used sometimes by application. Cf https://clang.llvm.org/doxygen/emmintrin_8h.html#a3aeb3a59d7de7f9ca49c1153baa9da58 for its definition
=> Add _MM_SHUFFLE2() macro for shuffle parameter for _mm_shuffle_pd()

README.md
We are happy users of sse2neon with https://github.com/OSGeo/gdal/pull/11202 and https://github.com/OSGeo/gdal/pull/11239
=> README.md: mention GDAL

.ci/check-format.sh, .ci/common.sh, .ci/cross-check.sh, .ci/cross-tool.sh, .github/workflows/main.yml, CONTRIBUTING.md, Makefile, sse2neon.h, tests/impl.cpp
The pre-built GNU compiler toolchain for various Arm targets. Version 14.2.Rel1.
=> CI: Update Arm GNU Toolchain and use Ubuntu 24.04

sse2neon.h
Regular malloc() should not be used for 1-byte aligned allocations, as such allocations cannot be freed correctly by _aligned_free().
Fixes #658
=> Fix mismatched _mm_{malloc,free} with LLVM/MinGW

Makefile, sse2neon.h, tests/impl.cpp, tests/main.cpp
When trying to compile [torzu](https://notabug.org/litucks/torzu) I got a bunch of errors originating from this library regarding the implicit int conversion. I patched it around by disabling `-Wconversion` but I figured it would be nice to address them here. The first commit enables this flag in the Makefile and fixes the resulting warnings. I've also made some minor improvements to the code I was touching.
I've also encountered `-Wshadow` errors because torzu is using `s64`, `f64`, and `u64` as type aliases and this library is using them as variable names. While these variable names are perfectly reasonable, I hope it's okay that I changed them in the second commit to avoid this. I've seen similar type aliases used elsewhere so keeping these variable names will probably trip up someone …
=> Enable `-Wconversion`

README.md
There was an typo in the URL, which cause the svg file can't display correctly:
=> Fix GitHub Action status badge

tests/impl.cpp
The issues in the linked bug reports have since been fixed.
=> run more tests when building with modern GCC
