DLTcollab/sse2neon

sse2neon.h
tests/impl.cpp
tests/impl.h

The arguments of _mm_set_epi8 are changed based on the webpage
https://msdn.microsoft.com/en-us/library/x0cx8zd3(v=vs.90).aspx

Add the unit testing of _mm_set_epi8

---

sse2neon.h
tests/impl.cpp
tests/impl.h

Add the corresponding unit testing.

Implement _mm_shuffle_epi8 with NEON instruction

---

sse2neon.h

The _mm_shuffle_epi8 conversion for ARM 32-bit architecure is added
since the NEON intrinsic function vqtbl1q_s8() is only supported
on ARM 64-bit architecture.

Support _mm_shuffle_epi8 on both ARM32 and Aarch64

---

sse2neon.h
tests/impl.cpp
tests/impl.h

Tested with `make check` on aarch64 and on x86_64 with the help of PR #21.

Implement loadh_pi and storeh_pi

---

sse2neon.h
tests/impl.cpp
tests/impl.h

Use longer version of NEON horizontal add.
Add testcase for _mm_hadd_epi16.

improve implementation of _mm_hadd_epi16

---

sse2neon.h
tests/impl.cpp
tests/impl.h

 Implement _mm_sra_epi16 and _mm_sra_epi32

---

.ci/cross-check.sh
.ci/cross-tool.sh
.travis.yml

Both arm and aarch64 targets are listed for Travis CI pipeline.

Preliminary CI pipeline for CROSS_COMPILE

---

sse2neon.h
tests/impl.cpp
tests/impl.h

feat: Implement _mm_minpos_epu16

---

sse2neon.h

These intrinsics likely were missed at the time -- they are an extension of the similar ones

Add missing extract_ps and subs_epi intrinsics

---

README.md

Some of the functions in test suite are based on the little-endian.

docs: Mention little-endian in test suite

---

sse2neon.h
tests/impl.cpp
tests/impl.h

Implement _mm_movehdup_ps and _mm_moveldup_ps

---

README.md

Add NEON Programmer's Guide which is a more comprehensive document
for NEON Intrinsics.

chore: Add NEON Programmer's Guide

---

sse2neon.h
tests/impl.cpp
tests/impl.h

Add _mm_add_pd for adding two double.

Implement _mm_add_pd

---

sse2neon.h
tests/impl.cpp

Implement A32 counterpart of _mm_store_pd

---

sse2neon.h
tests/common.cpp
tests/common.h
tests/impl.cpp
tests/impl.h

Add overloaded function, 'validateInt32' for testing datatype '__m64'.

Implement _mm_hadd_pi32

---

sse2neon.h
tests/impl.cpp
tests/impl.h

feat: Implement _mm_mulhi_pu16

---

sse2neon.h
tests/impl.cpp
tests/impl.h

Implement the tests of _mm_sad__[e]pu8 as well.
Close #139.

feat: Implement _mm_sad_pu8

---

sse2neon.h
tests/common.cpp
tests/common.h
tests/impl.cpp
tests/impl.h

feat: Implement _mm_castps_pd

---

sse2neon.h
tests/common.cpp
tests/common.h
tests/impl.cpp
tests/impl.h

Implement _mm_abs_pi{8,16,32} and the corresponding tests.
Implement the tests of _mm_abs_epi{8,16}.
Add the missing comments.

feat: Implement _mm_abs_pi{8,16,32}

---

tests/impl.cpp
tests/impl.h

The order is following the alphabetical order of each intrinsic class
Ref: https://software.intel.com/sites/landingpage/IntrinsicsGuide/

refactor: Reorder the intrinsic functions with class and alphabet

---

sse2neon.h
tests/impl.cpp

- test: Add tests for _mm_pack[u]s_epi{16,32}
- fix: Fix conversion of _mm_packus_epi32

Implement test and fix pack-related intrinsics

---

sse2neon.h
tests/impl.cpp

fix: Fix shift-related conversion and implement the tests

---

README.md

Add Minimap2 as software that adopts sse2neon

Update readme with Minimap2 as an example software that adopts sse2neon

---

sse2neon.h

The description and link of the official document is completed in this PR.

docs: Complete the lack of descriptions

---

tests/impl.cpp

Rearrange impl.cpp as the same order as impl.h.
close #267

refactor: Rearrange impl.cpp as the same order as impl.h

---

sse2neon.h
tests/impl.cpp

Dear all,
I have implemented _mm_cvtps_pi16.

Add intrinsics _mm_cvtps_pi16

---

sse2neon.h

The performance experiment result is recorded in issue #229.
Close #229.

perf: Improve performance of _mm_set_epi64x

---

sse2neon.h

Add GCC specific macro unlikely to enhance branch prediction.

feat: Add macro unlikely for branch prediction

---

sse2neon.h

The missing intrinsic has been added to gcc 7 on Amazon Linux 2, to gcc-8.5, and to gcc-9.4.
Using these compilers to compile sse2neon.h will start failing with multiple definitions of `vld1q_u8_x4`.
I see this error on Amazon Linux 2 with gcc-7.3.1-12:
```
g++ -o tests/common.o -Wall -Wcast-qual -I. -march=armv8-a+fp+simd+crc -std=gnu++14 -c -MMD -MF tests/common.o.d tests/common.cpp
In file included from tests/common.h:5:0,
from tests/common.cpp:1:
./sse2neon.h: In function ‘uint8x16x4_t vld1q_u8_x4(const uint8_t*)’:
./sse2neon.h:322:27: error: ‘uint8x16x4_t vld1q_u8_x4(const uint8_t*)’ redeclared inline without ‘gnu_inline’ attribute
FORCE_INLINE uint8x16x4_t vld1q_u8_x4(const uint8_t *p)
^~~~~~~~~~~
In file included from ./sse2neon.h:105:0,
from tests/common.h:5,
from …
```

avoid double declaration for vld1q_u8_x4

---

sse2neon.h

For embree/embree#316 and Blender integration to build without warnings.

Fix warnings about redefinition, uninitialized variables and unknown pragmas

---

sse2neon.h
tests/impl.cpp

feat: Implement intrinsics _mm_max_pd

---

sse2neon.h
tests/impl.cpp

feat: Implement intrinsics _mm_movemask_pi8

---

tests/impl.cpp

Add the checking of saturated minimum value for _mm_hadds_epi16
and saturated maximum value for _mm_hsubs_epi16.

fix: Fix the test of _mm_h[add|sub]s_epi16

---

sse2neon.h
tests/impl.cpp

The different rounding mode should be tested and implemented.

fix: Fix the test and implementation of _mm_cvtps_epi32

---

sse2neon.h
tests/impl.cpp

Extend the implementation to handle the different rounding mode.

feat: Add different rounding mode of _mm_cvt_[ps2pi|ss2si]

---

sse2neon.h
tests/impl.cpp

feat: Implement _mm_cvttpd_epi32

---

sse2neon.h
tests/impl.cpp

Extend the implementation to handle the different rounding mode.

feat: Add different rounding mode of _mm_cvtss_si[32|64]

---

sse2neon.h
tests/impl.cpp

feat: Implement _mm_cvtpd_(e)pi32

---

sse2neon.h
tests/impl.cpp

_mm_cmpnle_sd, _mm_cmpnlt_pd, _mm_cmpnlt_sd are added in this commit

feat: Implement compare not intrinsics

---

.ci/check-format.sh
.github/workflows/github_actions.yml
CONTRIBUTING.md
Makefile

Bump the version of clang-format from 6 to 11

---

sse2neon.h
tests/impl.cpp

The modification includes:
- Write the correct tests of _mm_cvtps_pi[8|16|32]
- Fix the original implementation of _mm_cvtps_pi16
- Implement _mm_cvtps_pi8
The test suite would check different rounding mode.
_mm_cvtps_pi[8|16] should set different output value based on the range
of the input value.
Take _mm_cvtps_pi16() for example:
0x7FFF(INT16_MAX) <= input <= 0x7FFFFFFF(INT32_MAX)
output = 0x7FFF(INT16_MAX)
0x8000(INT16_MIN) < input < 0x7FFF(INT16_MAX)
output = conversion from floating point to integer with corresponding roundinging mode
other input values
output = 0x8000(INT16_MIN)

feat: Implement and rewrite _mm_cvtps_pi[8|16|32]

---

sse2neon.h

fix: Fix wrong naming imm to imm8

---

tests/common.h
tests/impl.cpp

Replace the function of getting NaN value with C standard library function.
Remove unused code.

refactor: Get NaN value with C standard library

---

tests/impl.cpp

The extracted functions are refactored to avoid extra variable
declarations.

refactor: Extract unordered comparison as function

---

Makefile
sse2neon.h

Found via downstream https://github.com/embree/embree

Fix various typos

---

sse2neon.h

https://github.com/DLTcollab/sse2neon/issues/513

Fix _mm_storel_epi64

---

sse2neon.h
tests/common.h
tests/impl.cpp
tests/impl.h

feat: Implement _rdtsc

---

sse2neon.h
tests/impl.cpp

1. Implement `_mm_cmpestri` and `_mm_cmpestrm`.

Implement _mm_cmpestri and _mm_cmpestrm

---

sse2neon.h
tests/impl.cpp

fix: Align _mm_prefetch behavior to document

---

sse2neon.h
tests/impl.cpp

Implement `_mm_cmpistri` and `_mm_cmpistrm`.

Implement `_mm_cmpistri` and `_mm_cmpistrm`

---

sse2neon.h
tests/impl.cpp

Implement `_mm_cmpistra`, `_mm_cmpistrc`, `_mm_cmpistro`, `_mm_cmpistrs`, and `_mm_cmpistrz`.
Close #308.

Implement five `_mm_cmpistr`

---

tests/impl.cpp

Test all valid immediates in `_mm_dp_pd`.

Test all valid immediates in `_mm_dp_pd`

---

tests/impl.cpp

Using pure C implementation could enhance the maintainability, and reduce the dependency of other implementated functions in sse2neon.

test: Revise test of aeskeygenassist to C fashion

---

sse2neon.h
tests/impl.cpp
tests/impl.h

feat: Add _mm_aesimc_si128

---

tests/impl.cpp

fix: Fix exceeding width of type warning

---

sse2neon.h

Hello,
In this pull request, I have corrected a few minor typos.
Thank you for your time and consideration in reviewing these changes.
Best regards,
melody

docs: Fix the typos

---

sse2neon.h

closes #629
Slightly improve the error message to suggest users a way to fix the issue.

Improve unsupported target message

---

sse2neon.h

A simple PR to fix some typos caught by some code analysis tools.

Fix minor typos in the sse2neon header

---

sse2neon.h
sse2neon.sln
sse2neon.vcxproj
tests/common.h

This change adds support for Windows Arm64EC build through proper ifdefs.

Support Windows Arm64EC

---

sse2neon.h

Same changes as [HERE](https://github.com/DLTcollab/sse2neon/pull/674).
https://godbolt.org/z/rhG5vo4Wv

refactor: Improve readability of `_mm_movemask_pi8` & `_mm_movemask_ps`
